- platform: bayesian
  prior: 0.5
  name: 'AA Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.aa_iphone_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.aa_iphone'
      prob_given_true: 0.6
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'home'
    - entity_id: !secret device_tracker_owntracks_aa
      prob_given_true: 0.8
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.presence_a_homekit'
      prob_given_true: 0.7
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.google_maps_109462251504037679148'
      prob_given_true: 0.6
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
      
- platform: bayesian
  prior: 0.5
  name: 'PT Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.pt_iphone_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: !secret device_tracker_owntracks_pt
      prob_given_true: 0.8
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.google_maps_108800326647346833817'
      prob_given_true: 0.6
      prob_given_false: 0.3
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.presence_p_homekit'
      prob_given_true: 0.7
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'