language: python
python:
  - "3.6.4"
install:
  - pip3 install homeassistant==0.66.1
script:
  - hass -c $TRAVIS_BUILD_DIR --script check_config
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv dummysh addsecret.sh
  - mkdir $TRAVIS_BUILD_DIR/images
  - ls $TRAVIS_BUILD_DIR
  - bash $TRAVIS_BUILD_DIR/addsecret.sh
