homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret homeassistant_time_zone
  #add directory
  whitelist_external_dirs: 
    - !secret whitelist_external_dirs1
    - !secret whitelist_external_dirs2
  
  
  # Include the customizations.
  customize: !include customize.yaml      

# Show links to resources in log and frontend
# introduction:
#
# Enables the frontend

frontend:
  javascript_version: latest
  
# Enables configuration
config:

http:
  api_password: !secret http_api_password
  trusted_proxies:
    - !secret http_trusted_proxies
  trusted_networks:
    - !secret http_trusted_networks2
    - !secret http_trusted_networks3
    - !secret http_trusted_networks4
    - !secret http_trusted_networks5
    - !secret http_trusted_networks6
    - !secret http_trusted_networks7
  ip_ban_enabled: True
  login_attempts_threshold: 5
  use_x_forwarded_for: True
  base_url: !secret http_base_url
#  ssl_certificate: !secret http_ssl_certificate
#  ssl_key: !secret http_ssl_key

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
  
system_health:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger: !include logger.yaml
recorder: !include recorder.yaml  

system_log:
  fire_event: true

# Track the sun
sun:
      
weather:
  - platform: darksky
    api_key: !secret sensor_darksky_api_key 
        
    
# Text to speech
tts:
  - platform: google

xiaomi_aqara:
    gateways:
    - mac:
      key: !secret xiaomi_aquara_key1
      
notify:

  - name: iosnotify
    platform: group
    services:
        - service: ios_aa_iphone
        
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#notification'
    

apple_tv:
  - host: !secret apple_tv_host
    login_id: !secret apple_tv_login_id
    name: atv
    start_off: true

zeroconf:

climate:
  - platform: !secret climate_platform
    api_key: !secret climate_api_key1

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

media_player:
  - platform: webostv
    host: !secret media_player_webostv_host
    name: Living Room TV
    timeout: 5
    turn_on_action:
      service: media_player.turn_on
      entity_id: media_player.atv

  - platform: denonavr
    name: Living Room Receiver
    show_all_sources: True

  - platform: universal
    name: Universal
    children:
      - media_player.living_room_tv
      - media_player.marantz_sr6010
    commands:
      turn_on:
        service: media_player.turn_on
        data: 
          entity_id: media_player.living_room_tv
      turn_off:
        service: media_player.turn_off
        data: 
          entity_id: media_player.living_room_tv
      volume_up:
        service: media_player.volume_up
        data: 
          entity_id: media_player.marantz_sr6010
      volume_down:
        service: media_player.volume_down
        data: 
          entity_id: media_player.marantz_sr6010
      volume_set:
        service: media_player.volume_set
        data: 
          entity_id: media_player.marantz_sr6010
      volume_mute:
        service: media_player.volume_mute
        data: 
          entity_id: media_player.marantz_sr6010
      select_source:
        service: input_select.select_option
        data_template: 
          entity_id: input_select.media_source
          option: '{{ source }}'
    attributes:
      is_volume_muted: media_player.marantz_sr6010|is_volume_muted
      volume_level: media_player.marantz_sr6010|volume_level
      state: media_player.living_room_tv
      source: input_select.media_source
      source_list: input_select.media_source|options

python_script:

zwave:
  usb_path: !secret zwave_usb_path
  network_key: !secret zwave_network_key

ffmpeg:
  ffmpeg_bin: /usr/local/Cellar/ffmpeg/3.4/bin/ffmpeg
  
homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - binary_sensor
      - climate
      - sensor
      - switch
      - input_boolean
    exclude_entities:
      - input_boolean.alarm_home_triggered
      - input_boolean.alarm_silence
      - input_boolean.ha_start
      - sensor.dark_sky_daytime_high_temperature
      - sensor.dark_sky_overnight_low_temperature
      - sensor.dark_sky_apparent_temperature
      - binary_sensor.ftp_server
      - binary_sensor.homebridge_server
      - binary_sensor.internet_link
      - binary_sensor.camera_1
      - binary_sensor.camera_2
      - binary_sensor.camera_3
      - binary_sensor.camera_4
      - binary_sensor.camera_5
      - sensor.multisensor1_dew_point
      - sensor.multisensor1_co2_level
  entity_config:
    alarm_control_panel.home_alarm:
      code: 1234
#    media_player.living_room:
#     feature_list:
#      - feature: on_off
    switch.switch1_switch:
      type: outlet
  auto_start: False

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: hass
  username: !secret mqtt_username
  password: !secret mqtt_password
  
light:
  - platform: switch
    name: Lounge spotlight
    entity_id: switch.switch5_switch

alarm_control_panel: !include alarm_control_panel.yaml
automation: !include_dir_merge_list automation
binary_sensor: !include_dir_merge_list binary_sensor
camera: !include_dir_merge_list camera
device_tracker: !include_dir_merge_list device_tracker
#group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_text: !include_dir_merge_named input_text
ios:
  push:
    categories: !include_dir_merge_list ios
#scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include zones.yaml

