###################################################
####
#### climate automation linked to python
- alias: climate automation
  trigger:
  - platform: template
    value_template: '{% if states.binary_sensor.occupancy_mainbedroom.state == "on" and states.sensor.multisensor2_temperature.state | float > 26.9 and as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.climate.master_bedroom.last_changed) |int > 240 %}True{% endif %}'
  - platform: template
    value_template: '{% if states.sensor.multisensor2_temperature.state | float < 26.9 and as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.climate.master_bedroom.last_changed) |int > 240 %}True{% endif %}'
  - platform: template
    value_template: '{% if states.sensor.multisensor2_temperature.state | float < 25.0 and as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.climate.master_bedroom.last_changed) |int > 240 %}True{% endif %}'
  - platform: template
    value_template: '{% if as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) - as_timestamp(states.climate.master_bedroom.last_changed) |int > 1320 %}True{% endif %}'
  - platform: state
    entity_id: binary_sensor.occupancy_mainbedroom
    to: 'off'
    for:
      minutes: 2
  - platform: time 
    minutes: /15
    seconds: 0
  action:
  - service: python_script.climate
    data_template:
      trigger_entity: '{{trigger.entity_id}}'
