    
    
- action:
  - data_template:
      message: >
        Entity_ID: {{ trigger.to_state.entity_id }}.
        Friendly_name: {{trigger.to_state.attributes.friendly_name}}.
        State to: {{trigger.to_state.state}}.
        State from: {{trigger.from_state.state}}.
        State last updated: {{trigger.to_state.last_updated}}.
        State last changed: {{trigger.to_state.last_changed}}. 
        State last updated1: {{trigger.from_state.last_updated}}.
        State last changed1: {{trigger.from_state.last_changed}}. 
        {%- set nowtime = as_timestamp(strptime(states.sensor.date__time.state, "%Y-%m-%d, %H:%M")) %}
        {%- set lastchg = as_timestamp(states.sensor.camera2_http.last_changed) %}           
        {%- set lastchgHA = as_timestamp(states.input_boolean.HA_start.last_changed) %}
        {%- set sec = (nowtime - lastchg) | int %}
        {%- set secHA = (nowtime - lastchgHA) | int -%}
        sec {{ sec }} = {{ nowtime }} - {{lastchg}}
        secHA {{ secHA}} = {{ nowtime }} - {{lastchgHA}}
    service: notify.allnotify
  alias: Binary sensor testing camera 2
  initial_state: 'off'
  condition: []
  id: '1517815434000'
  trigger:
  - entity_id: 
    - binary_sensor.camera2_motion
    - sensor.camera2_http
    platform: state

###################################################
####
#### TESTING light turn on / off based on light and sun
####
###################################################
###################################################
####
#### Turn on light if (door open) and light is dark and sun is down
- action:
  - data:
      message: testing all conditions met
    service: notify.allnotify
  alias: Turn on light if after sunset (testing)
  initial_state: 'off'
  condition:
  - condition: numeric_state
    below: '0.1'
    entity_id: sensor.multisensor1_luminance
  - condition: numeric_state
    below: '-5'
    entity_id: sun.sun
    value_template: '{{states.sun.sun.attributes.elevation}}'
  id: '1508324243362'
  trigger:
  - entity_id: light.gateway_light_f0b429b3ddc0
    platform: state
    to: 'on'
